name: Release

on:
  workflow_run:
    workflows: ['e2e']
    branches: [main, beta]
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Use deps cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ./.yarn/cache
          key: deps-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install --immutable

      - name: Set git config
        run: |
          git config --global user.name 'Tobias Høegh'
          git config --global user.email 'tobias@tujo.no'

      - name: Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn workspace gatsby-plugin-eufemia-theme-handler release
